sonar.projectKey=denysdanilievskyi-byte_SomeoneHere-git.github.io
sonar.organization=denysdanilievskyi-byte
sonar.projectName=SomeoneHere-git.github.io
sonar.projectVersion=1.0
sonar.sources=lab3/src
sonar.tests=lab3/tests
sonar.language=cfamily
sonar.sourceEncoding=UTF-8