name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Analyze
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          
      - name: Configure CMake (Generate compile_commands.json)
        # На Windows используем MinGW, чтобы CMAKE_EXPORT_COMPILE_COMMANDS сработал
        run: cmake -G "MinGW Makefiles" -S ./lab3 -B ./lab3/build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # Розкоментуйте, якщо сервер університетський, а не SonarCloud
        with:
          args: >
            -Dsonar.projectKey=ТУТ_МАЄ_БУТИ_ВАШ_КЛЮЧ_ПРОЄКТУ
            -Dsonar.sources=lab3/src
            -Dsonar.cfamily.compile-commands=lab3/build/compile_commands.json