name: C++ Unit Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # Говорим GitHub выполнять все команды внутри папки lab3
    defaults:
      run:
        working-directory: ./lab3

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev lcov

      - name: Configure CMake (Creates build folder)
        run: cmake -S . -B build -DENABLE_COVERAGE=ON

      - name: Build
        run: cmake --build build -j4

      - name: Run Tests
        run: ./build/lab3_tests

      - name: Generate Coverage Report
        run: |
          cd build
          lcov --capture --directory . --output-file cov.info --ignore-errors mismatch
          lcov --remove cov.info '/usr/*' -o cov_filtered.info
          lcov --summary cov_filtered.info
